---
title: "ARIMA_Time_Series_Analysis"
author: "Max Dippel"
date: "11/5/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Loading libraries

library(nlme)
library(spatstat)
library(quantreg)
library(fBasics)
library(nls2)
library(MASS)
library(car)
library(MuMIn)
library(ggplot2)

```

```{r}
# loading the dataset

tree <- read.csv("treering.csv")
head(tree)

```

```{r}
# Plotting the raw data

plot(trw ~ year, data=tree, type="l", pch=16, 
     ylab="Tree Ring Width", xlab="Year")
plot(trw ~ year, data=tree, type="l", pch=16, 
     ylab="Tree Ring Width", xlab="Year")
ggplot(data = tree, aes(x=year, y= trw)) + geom_line()

# From this graph we can see that 

```

```{r}

# Creating a partial auto-correlation function graph

pacf <- pacf(tree$trw, main="PACF")

# With this graph you can see that there is 
```



```{r}


pacf <- pacf(tree$trw, main="PACF")

lm1 <- lm(trw ~ year, data=tree)
summary (lm1)
confint(lm1, "(Intercept)", level = .95)
confint(lm1, "year", level = .95)
#
#
tree$mod.resid <- residuals(lm1)
pacf <- pacf(tree$mod.resid, main="PACF - tree ring residuals")
?pacf()

# AR 
ar.1 <- arima(tree$mod.resid, order=c(1,0,0)) 
ar.2 <- arima(tree$mod.resid, order=c(2,0,0))
ar.3 <- arima(tree$mod.resid, order=c(3,0,0))
ar.4 <- arima(tree$mod.resid, order=c(4,0,0))
ar.5 <- arima(tree$mod.resid, order=c(5,0,0))
# MA
ma.1 <- arima(tree$mod.resid, order=c(0,0,1)) 
ma.2 <- arima(tree$mod.resid, order=c(0,0,2)) 
ma.3 <- arima(tree$mod.resid, order=c(0,0,3)) 
ma.4 <- arima(tree$mod.resid, order=c(0,0,4)) 
ma.5 <- arima(tree$mod.resid, order=c(0,0,5)) 
?arima()
AICc(ar.1)
AICc(ar.2)
AICc(ar.3)
AICc(ar.4)
AICc(ar.5)
AICc(ma.1)
AICc(ma.2)
AICc(ma.3)
AICc(ma.4)
AICc(ma.5)

gls.mod1 <- gls(trw ~ year, data=tree, correlation = corARMA(p=2, q=0))
gls.mod2 <- gls(trw ~ year, data=tree, correlation = corARMA(p=0, q=3))
gls.mod3 <- gls(trw ~ year, data=tree, correlation = corARMA(p=3, q=0))
gls.mod4 <- gls(trw ~ year, data=tree, correlation = corARMA(p=0, q=4))

?gls()

AICc(gls.mod1)
AICc(gls.mod2)
AICc(gls.mod3)
AICc(gls.mod4)

summary(gls.mod1)
confint(gls.mod1)

tree$new.residuals <- resid(gls.mod1, type="normalized")

pacf2 <- pacf(tree$new.residuals, main="PACF - GLS model residuals")
```


